### ISSUE TITLE
Invalid _to recepient

### ISSUE THREAD

**Issue by karanrajpal14** [danielireson/formplug-serverless#19]
Hello,

I'm having trouble getting this work. I've deployed the backend and I'm trying to test it via Postman. Here's what the curl call looks like:
```
curl --location --request POST 'https://hgwaf31jxa.execute-api.us-west-2.amazonaws.com/dev/?format=json' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------505726920421207878101501' \
--form '_to=rajpal.karan73@gmail.com' \
--form 'message=test \
--form 'name=test' \
--form 'email=test'
```

The response is:
```
{
    "statusCode": 422,
    "message": "Invalid '_to' recipient"
}
```

I've completed my SES verification and also tried adding my email to the whitelisted domains array but to no avail. I've also tried using the encrypted email but that doesn't work either. Mind helping me out?

**Comment by danielireson** [comment]
Hi Karen, it looks like you are sending the data with the wrong content type - I can see `multipart/form-data` in the header instead of `application/x-www-form-urlencoded`.

Have a look at [this stackoverflow answer](https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data) for more information on this.
