### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by viraf** [danielireson/formplug-serverless#4]
I followed this guide and keep getting Internal Server Error how do I resolve this ?

I am using this example

                <form action="https://my api gateway url/to/my verified email address" method="post">
                    <input type="text" name="name">
                    <input type="submit" value="Send">

Even the form on your site is not working

**Comment by danielireson** [comment]
Hi Viraf, i'll take a look this properly later. So just to confirm, you get a HTTP 500 Internal Server Error and not HTTP 502 Bad Gateway? I suspect it's related to the email address that you're either trying to send to or have verified. It looks like the error from AWS SES is getting discarded, which isn't helpful. I've replicated locally and on the docs website that a 502 happens when sending messages to an invalid email address (e.g. johndoe@example.com).

**Comment by viraf** [comment]
Thanks Daniel

I too am getting a 502 Bad Gateway Error. Just checked in an http client. I can confirm that I am using a verified email address in the form action.

**Comment by viraf** [comment]
Hi Daniel, With further testing I found that the encrypted email address endpoint works as expected but the plain text one doesn't.

**Comment by danielireson** [comment]
Glad you got it working with the encrypted string. Do you mind sharing the email address you were trying to send to? It would be great to check it against the regex pattern used for validation. Feel free to send it to me over email if you don't want to disclose it publicly - danielireson@gmail.com.

**Comment by viraf** [comment]
My bad. The issue was with the configuration. I was using the ENCRYPTION_KEY in config.json and not using the encrypted POST url.
